# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1269a26c04a3b880db9b2d905809eb56bb78b29d38c13c40baf953af728552acddc5476885da9fd40e366681a094344186e6177a14098797dbdd78158c9e34ef

test:
  secret_key_base: d4d29a291893d34ac82c45611376798db97b4c23079bdd0312396f7f75719e1b4e1df38a4e47f5514b428837686057a72d532cdedc5720e53e830f02ec822be5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
